package src

func Euler2(top int64) int64 {
	// Each new term in the Fibonacci sequence is
	// generated by adding the previous two terms.
	// By starting with 1 and 2, the first 10 terms will be:
	// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	// By considering the terms in the Fibonacci
	// sequence whose values do not exceed four million,
	// find the sum of the even-valued terms.
	var i int64 = 1
	var sum int64 = 0
	a, b, c := 1, 2, 3
	for i = 1; i <= top; i++ {
		// print(a, " ")
		if a%2 == 0 {
			sum += int64(a)
		}

		c = a + b
		a = b
		b = c
	}

	println("Euler2 ", top, "=", sum)
	// 1 2 3 5 8 13 21 34 55 89 Euler2  10 = 44

	return sum
}
